using UnityEngine;
using UnityEngine.AI;

// Use physics raycast hit from mouse click to set agent destination
[RequireComponent(typeof(NavMeshAgent))]
public class ClickToMove : MonoBehaviour
{
    NavMeshAgent m_Agent;
    RaycastHit m_HitInfo = new RaycastHit();

    void Start()
    {
        m_Agent = GetComponent<NavMeshAgent>();
        m_Agent.speed = 4.5f;
        m_Agent.angularSpeed = 500;
        m_Agent.acceleration = 20;
    }

    void Update()
    {
        if (Input.GetMouseButtonDown(0) && !Input.GetKey(KeyCode.LeftShift))
        {
            var ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            if (Physics.Raycast(ray.origin, ray.direction, out m_HitInfo))
                m_Agent.destination = m_HitInfo.point;
        }
        Debug.Log("speed: "+m_Agent.speed);
        Debug.Log("angularSpeed: "+m_Agent.angularSpeed);
        Debug.Log("acceleration: "+m_Agent.acceleration);
    }
}
